### ISSUE TITLE
Watcher occasionally drops keys

### ISSUE THREAD

**Issue by pyuxiang** [s-fifteen-instruments/guardian#18]
Watcher is observed to suddenly drop keys in contiguous batches at a time. This seems to be attributed to an error raised when watcher attempts to verify capabilities with vault, perhaps from the loss of authentication due to expired token. Logs attached below:

<details>
<summary>watcher stdout</summary>

```
...
INFO:root:Vault write "QKDE0001/slavemaster/status" version 27136 successful
INFO:root:Filename: /epoch_files/beabe5c0; Worker result: {'/epoch_files/beabe5c0': True}
INFO:root:Vault write "QKDE0001/masterslave/status" version 27986 successful
INFO:root:Filename: /epoch_files/beabe5c1; Worker result: {'/epoch_files/beabe5c1': True}
WARNING:root:Worker for: /epoch_files/beabe5c3 generated an exception: None
WARNING:root:Worker for: /epoch_files/beabe5c4 generated an exception: None
...
WARNING:root:Worker for: /epoch_files/beabf061 generated an exception: None
WARNING:root:Worker for: /epoch_files/beabf062 generated an exception: None
INFO:root:"watcher" is now authenticated
INFO:root:Vault write "QKDE0001/masterslave/status" version 27989 successful
INFO:root:Filename: /epoch_files/beabf063; Worker result: {'/epoch_files/beabf063': True}
INFO:root:Vault write "QKDE0001/slavemaster/status" version 27138 successful
INFO:root:Filename: /epoch_files/beabf064; Worker result: {'/epoch_files/beabf064': True}
...
```

</details>

<details>
<summary>watcher stderr</summary>

```
Traceback (most recent call last):
  File "/root/code/watcher.py", line 558, in mainloop
    result = future.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/code/watcher.py", line 458, in process_epoch_file
    self.vault_write_key(epoch, raw_key,
  File "/root/code/watcher.py", line 282, in vault_write_key
    self.vault_can_create_new_keys(full_filepath=full_path)
  File "/root/code/watcher.py", line 110, in vault_can_create_new_keys
    self.vclient.sys.get_capabilities(paths=full_filepath)
  File "/usr/local/lib/python3.9/site-packages/hvac/api/system_backend/capabilities.py", line 40, in get_capabilities
    return self._adapter.post(
  File "/usr/local/lib/python3.9/site-packages/hvac/adapters.py", line 159, in post
    return self.request("post", url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/hvac/adapters.py", line 408, in request
    response = super().request(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/hvac/adapters.py", line 376, in request
    self._raise_for_error(method, url, response)
  File "/usr/local/lib/python3.9/site-packages/hvac/adapters.py", line 294, in _raise_for_error
    utils.raise_for_error(
  File "/usr/local/lib/python3.9/site-packages/hvac/utils.py", line 41, in raise_for_error
    raise exceptions.VaultError.from_status(
hvac.exceptions.Forbidden: permission denied, on post https://vault:8200/v1/sys/capabilities-self
```

</details>

Durations during which keys are dropped was observed to be {1460, 1131, 1195, ...} seconds, so it doesn't seem to be a timeout-related resolution.

**Comment by pyuxiang** [comment]
Currently cannot be reproduced in the latest commits.
